export * from './accountResource.service';
import { AccountResourceService } from './accountResource.service';
export * from './customerDetailsResource.service';
import { CustomerDetailsResourceService } from './customerDetailsResource.service';
export * from './productCategoryResource.service';
import { ProductCategoryResourceService } from './productCategoryResource.service';
export * from './productOrderResource.service';
import { ProductOrderResourceService } from './productOrderResource.service';
export * from './productResource.service';
import { ProductResourceService } from './productResource.service';
export * from './publicUserResource.service';
import { PublicUserResourceService } from './publicUserResource.service';
export * from './shoppingCartResource.service';
import { ShoppingCartResourceService } from './shoppingCartResource.service';
export * from './userJwtController.service';
import { UserJwtControllerService } from './userJwtController.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export const APIS = [AccountResourceService, CustomerDetailsResourceService, ProductCategoryResourceService, ProductOrderResourceService, ProductResourceService, PublicUserResourceService, ShoppingCartResourceService, UserJwtControllerService, UserResourceService];
