/**
 * Store API
 * Store API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductDTO } from './productDTO';
import { ShoppingCartDTO } from './shoppingCartDTO';

export interface ProductOrderDTO { 
    id?: number;
    quantity: number;
    totalPrice: number;
    product?: ProductDTO;
    cart?: ShoppingCartDTO;
}