/**
 * Store API
 * Store API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductCategoryDTO } from './productCategoryDTO';

/**
 * Product sold by the Online store
 */
export interface ProductDTO { 
    id?: number;
    sku: string;
    upc: string;
    ean: string;
    name: string;
    description?: string;
    price: number;
    productSize: ProductDTO.ProductSizeEnum;
    colors?: string;
    image?: Array<string>;
    imageContentType?: string;
    imageSha1?: string;
    imageCdnUrl?: string;
    thumbnailSha1?: string;
    thumbnailCdnUrl?: string;
    productCategory?: ProductCategoryDTO;
}
export namespace ProductDTO {
    export type ProductSizeEnum = 'S' | 'M' | 'L' | 'XL' | 'XXL';
    export const ProductSizeEnum = {
        S: 'S' as ProductSizeEnum,
        M: 'M' as ProductSizeEnum,
        L: 'L' as ProductSizeEnum,
        XL: 'XL' as ProductSizeEnum,
        XXL: 'XXL' as ProductSizeEnum
    };
}