# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzAxMGFiMjg3OGRhYjFlMzFiZmI4NTc1NGRiMjdkMTAzMTkxZmEwMmU3ZTM1NzNhMjJiMjA1NmFjOGRmZDU5ZjI3MzE1NTA0OWY2ODkzYTlkZTg0MWI2MmM3YjU2NGNjMzhjNzY3YWE1ZTNkMTAyNGU3MjEwZTdkMjA4YjhlOWI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
