# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzFjNTUxNDk3MGI1MzVhMzcyMzlhMTZjNzMxNzFlZjE0ZjBjYzRjNWNmMGY4M2M1MmY0OTk1OWIwNzI0ZWY4NTY3YTc4ZDQzZTk2NzJiZjFiY2Y5ZmI1YWFjNWY2NGMxNWY3OTk0Mzk4NmY5N2I2NTUzNzhhMmRhNzkzODllMDY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
