/*
 * Store API
 *
 * Store API documentation
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type AdminUserDto struct {

	Id int64 `json:"id,omitempty"`

	Login string `json:"login"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Email string `json:"email,omitempty"`

	ImageUrl string `json:"imageUrl,omitempty"`

	Activated bool `json:"activated,omitempty"`

	LangKey string `json:"langKey,omitempty"`

	CreatedBy string `json:"createdBy,omitempty"`

	CreatedDate time.Time `json:"createdDate,omitempty"`

	LastModifiedBy string `json:"lastModifiedBy,omitempty"`

	LastModifiedDate time.Time `json:"lastModifiedDate,omitempty"`

	Authorities []string `json:"authorities,omitempty"`
}
