apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-app
  namespace: store
  labels:
    team: store
spec:
  selector:
    matchLabels:
      app: notification
  endpoints:
    - port: http
      path: /management/prometheus
