# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginVM(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None, password: str=None, remember_me: bool=None):  # noqa: E501
        """LoginVM - a model defined in Swagger

        :param username: The username of this LoginVM.  # noqa: E501
        :type username: str
        :param password: The password of this LoginVM.  # noqa: E501
        :type password: str
        :param remember_me: The remember_me of this LoginVM.  # noqa: E501
        :type remember_me: bool
        """
        self.swagger_types = {
            'username': str,
            'password': str,
            'remember_me': bool
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'remember_me': 'rememberMe'
        }
        self._username = username
        self._password = password
        self._remember_me = remember_me

    @classmethod
    def from_dict(cls, dikt) -> 'LoginVM':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginVM of this LoginVM.  # noqa: E501
        :rtype: LoginVM
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this LoginVM.


        :return: The username of this LoginVM.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this LoginVM.


        :param username: The username of this LoginVM.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this LoginVM.


        :return: The password of this LoginVM.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginVM.


        :param password: The password of this LoginVM.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def remember_me(self) -> bool:
        """Gets the remember_me of this LoginVM.


        :return: The remember_me of this LoginVM.
        :rtype: bool
        """
        return self._remember_me

    @remember_me.setter
    def remember_me(self, remember_me: bool):
        """Sets the remember_me of this LoginVM.


        :param remember_me: The remember_me of this LoginVM.
        :type remember_me: bool
        """

        self._remember_me = remember_me
