# coding: utf-8

"""
    Store API

    Store API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.user_resource_api import UserResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserResourceApi(unittest.TestCase):
    """UserResourceApi unit test stubs"""

    def setUp(self):
        self.api = api.user_resource_api.UserResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        """
        pass

    def test_get_all_users(self):
        """Test case for get_all_users

        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_update_user(self):
        """Test case for update_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
