# coding: utf-8

"""
    Store API

    Store API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.public_user_resource_api import PublicUserResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPublicUserResourceApi(unittest.TestCase):
    """PublicUserResourceApi unit test stubs"""

    def setUp(self):
        self.api = api.public_user_resource_api.PublicUserResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_public_users(self):
        """Test case for get_all_public_users

        """
        pass

    def test_get_authorities(self):
        """Test case for get_authorities

        """
        pass


if __name__ == '__main__':
    unittest.main()
