# coding: utf-8

"""
    Store API

    Store API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.user_jwt_controller_api import UserJwtControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserJwtControllerApi(unittest.TestCase):
    """UserJwtControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.user_jwt_controller_api.UserJwtControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authorize(self):
        """Test case for authorize

        """
        pass


if __name__ == '__main__':
    unittest.main()
