# coding: utf-8

"""
    Store API

    Store API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.shopping_cart_resource_api import ShoppingCartResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestShoppingCartResourceApi(unittest.TestCase):
    """ShoppingCartResourceApi unit test stubs"""

    def setUp(self):
        self.api = api.shopping_cart_resource_api.ShoppingCartResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_shopping_cart(self):
        """Test case for create_shopping_cart

        """
        pass

    def test_delete_shopping_cart(self):
        """Test case for delete_shopping_cart

        """
        pass

    def test_get_all_shopping_carts(self):
        """Test case for get_all_shopping_carts

        """
        pass

    def test_get_shopping_cart(self):
        """Test case for get_shopping_cart

        """
        pass

    def test_partial_update_shopping_cart(self):
        """Test case for partial_update_shopping_cart

        """
        pass

    def test_update_shopping_cart(self):
        """Test case for update_shopping_cart

        """
        pass


if __name__ == '__main__':
    unittest.main()
