# coding: utf-8

"""
    Store API

    Store API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.password_change_dto import PasswordChangeDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestPasswordChangeDTO(unittest.TestCase):
    """PasswordChangeDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPasswordChangeDTO(self):
        """Test PasswordChangeDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.password_change_dto.PasswordChangeDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
