# coding: utf-8

"""
    Store API

    Store API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.product_order_resource_api import ProductOrderResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductOrderResourceApi(unittest.TestCase):
    """ProductOrderResourceApi unit test stubs"""

    def setUp(self):
        self.api = api.product_order_resource_api.ProductOrderResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_product_order(self):
        """Test case for create_product_order

        """
        pass

    def test_delete_product_order(self):
        """Test case for delete_product_order

        """
        pass

    def test_get_all_product_orders(self):
        """Test case for get_all_product_orders

        """
        pass

    def test_get_product_order(self):
        """Test case for get_product_order

        """
        pass

    def test_partial_update_product_order(self):
        """Test case for partial_update_product_order

        """
        pass

    def test_update_product_order(self):
        """Test case for update_product_order

        """
        pass


if __name__ == '__main__':
    unittest.main()
