# coding: utf-8

"""
    Store API

    Store API documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.jwt_token import JWTToken  # noqa: E501
from swagger_client.rest import ApiException


class TestJWTToken(unittest.TestCase):
    """JWTToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJWTToken(self):
        """Test JWTToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.jwt_token.JWTToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
