<?php
/**
 * ShoppingCartResourceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Store API
 *
 * Store API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ShoppingCartResourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShoppingCartResourceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createShoppingCart
     *
     * .
     *
     */
    public function testCreateShoppingCart()
    {
    }

    /**
     * Test case for deleteShoppingCart
     *
     * .
     *
     */
    public function testDeleteShoppingCart()
    {
    }

    /**
     * Test case for getAllShoppingCarts
     *
     * .
     *
     */
    public function testGetAllShoppingCarts()
    {
    }

    /**
     * Test case for getShoppingCart
     *
     * .
     *
     */
    public function testGetShoppingCart()
    {
    }

    /**
     * Test case for partialUpdateShoppingCart
     *
     * .
     *
     */
    public function testPartialUpdateShoppingCart()
    {
    }

    /**
     * Test case for updateShoppingCart
     *
     * .
     *
     */
    public function testUpdateShoppingCart()
    {
    }
}
